### ISSUE TITLE
plant_erd_darwin_arm64 doesn't work on Apple M1

### ISSUE THREAD

**Issue by sue445** [sue445/plant_erd#160]
`plant_erd_darwin_arm64 sqlite3` doesn't works on Mac (M1), but `plant_erd_darwin_amd64 sqlite3` works on Mac (M1) 😇 

```
$ uname -m
arm64

$ ./plant_erd_darwin_amd64 sqlite3 --database test-sqlite3.db

$ ./plant_erd_darwin_arm64 sqlite3 --database test-sqlite3.db
2021/09/09 15:39:43 Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

I want to use Apple M1 on CI build, but GitHub Actions doesn't support yet.

https://github.com/actions/virtual-environments/issues/2187

# Workarround 
* Use `plant_erd_darwin_amd64`
* Build on your pc (use `make`)

**Comment by Wesseldr** [comment]
On M1Max MacOs 14.1 plant_erd version v0.4.4 (build. 866b345) worked on a sqlite3 DB as expected (PlantUML format)

**Comment by sue445** [comment]
[GitHub Actions: Introducing the new M1 macOS runner available to open source\! \- The GitHub Blog](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/) 

🎉
